#!/bin/bash
# Generates a Windows-like identity for the sing-rdp server:
#
#   - hostname:  DESKTOP-XXXXXXX (7 uppercase alphanumerics, NetBIOS-fitting)
#   - cert:      self-signed, CN matching hostname, 180-day validity,
#                no SAN, sha256WithRSAEncryption — same shape as the
#                cert Windows generates for its built-in RDP service
#   - cookie:    pseudo-username, e.g. "user-1234"
#
# Outputs (env vars exported into stdout when sourced, or written to
# files when invoked):
#
#   $CERT_DIR/cert.pem
#   $CERT_DIR/key.pem
#   $ENV_FILE     (SING_RDP_HOSTNAME, SING_RDP_COOKIE, etc.)

set -euo pipefail

CERT_DIR="${CERT_DIR:-./certs}"
ENV_FILE="${ENV_FILE:-./.env}"
FORCE="${FORCE:-0}"

random_hostname() {
    # Windows uses [A-Z0-9] but excludes ambiguous chars (0/O/1/I) on
    # newer builds. We follow that convention.
    local suffix
    suffix=$(LC_ALL=C tr -dc 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789' </dev/urandom | head -c 7)
    echo "DESKTOP-${suffix}"
}

random_cookie() {
    # Common in-the-wild username patterns:
    #   user-1234, svc-rdp, jumpbox, admin
    # We use "user-NNNN" because it's the most generic.
    local n=$((1000 + RANDOM % 9000))
    echo "user-${n}"
}

generate_cert() {
    local hostname="$1"
    mkdir -p "$CERT_DIR"
    # Match Windows RDP cert shape:
    #   - sha256WithRSAEncryption  (-sha256 -newkey rsa:2048)
    #   - 180-day validity         (-days 180)
    #   - no SAN, just CN          (-subj "/CN=...", no -addext)
    #   - basicConstraints CA:FALSE is the openssl default when -extensions
    #     isn't passed
    openssl req -x509 \
        -newkey rsa:2048 \
        -sha256 \
        -days 180 \
        -nodes \
        -subj "/CN=${hostname}" \
        -keyout "${CERT_DIR}/key.pem" \
        -out "${CERT_DIR}/cert.pem" \
        >/dev/null 2>&1
    chmod 600 "${CERT_DIR}/key.pem"
}

main() {
    if [[ -f "$ENV_FILE" && "$FORCE" != "1" ]]; then
        echo "$ENV_FILE already exists; refusing to overwrite (set FORCE=1 to override)" >&2
        exit 1
    fi

    local hostname cookie
    hostname=$(random_hostname)
    cookie=$(random_cookie)

    generate_cert "$hostname"

    cat > "$ENV_FILE" <<EOF
# Generated by generate-identity.sh on $(date -u +%FT%TZ)
# Do NOT check this file into source control — it contains the cookie
# secret that gates tunnel access.
SING_RDP_HOSTNAME=${hostname}
SING_RDP_COOKIE=${cookie}
SING_RDP_SNI=${hostname}
SING_RDP_NETBIOS_DOMAIN=WORKGROUP
EOF
    chmod 600 "$ENV_FILE"

    echo "generated identity:"
    echo "  hostname:  ${hostname}"
    echo "  cookie:    ${cookie}"
    echo "  cert:      ${CERT_DIR}/cert.pem (CN=${hostname}, 180-day, sha256RSA)"
    echo "  env file:  ${ENV_FILE}"
}

main "$@"
